myblog3/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # music/12/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailsView.as_view(), name="detail"),

    # music/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add')
]

myblog3/music/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.urls import reverse
from django.http import HttpResponseRedirect


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        # return reverse('music:detail', kwargs={'pk': self.pk})
        return HttpResponseRedirect('/music/')

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

myblog3/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_album'

    def get_queryset(self):
        return Album.objects.all()


class DetailsView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']



myblog3/music/templates/music/album_form.html
{%extends 'music/base.html'%}
{%block title%}Add Album {%endblock%}

{% block body %}

<form class=form-horizontal" action="" method="post" enctype="multipart/form-data" >
    {%csrf_token%}
    {%include 'music/form-template.html'%}
    <div class="form-group">
    <div class=" col sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-success">Add New Album</button>
    </div>
    </div>
</form>



{% endblock %}

myblog3/music/templates/music/base.html
<!DOCTYPE html>

<html lang="en">
	<head>
		<meta charset="YTF-8">
		<title>
		{%block title%}
		
		{%endblock%}
		</title>
		
		{%load staticfiles%}
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="{%static 'music/style.css'%}" />
		<link rel="stylesheet" type="text/css" href="{%static 'music/index.css'%}" />
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	</head>
	<body>
	
	<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{%url 'music:index' %}"> Viberr </a>
		</div>
		
		<div class="collapse navbar-collapse" id="topNavBar">
			<ul class="nav navbar-nav">
				<li class="">
					<a href="{%url 'music:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums </a>
				</li>
				<li class="">
					<a href="#"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs </a>
				</li>
			</ul>
			
			<form class="navbar-form navbar-left" role="search" method="post" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>
			
			<ul class="nav navbar-nav navbar-right ">
				<li class="">
					<a href="{%url 'music:album-add' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album</a>
				</li>
				
				<li class="">
					<a href="{%url 'music:index' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; LogOut</a>
				</li>
			</ul>
			
		</div>
	</div>
</nav>
	
	{% block body %}
	{%endblock%}
	
	

</body>
</html>

myblog3/music/templates/music/detail.html
{%extends 'music/base.html'%}
{%block title%}Album Details{%endblock%}


{% block body %}
<img src="{{album.album_logo}}">

<h1>{{album.album_title}}</h1>
<h3>{{ album.artist }}</h3>

{% if error_message %}
	<p><strong>{{error_message}}</strong></p>
{%endif%}

{%for song in album.song_set.all %}
	
	<i>
		{{song.song_title}} - {{song.file_type}}
	</i><br>
{% endfor %}

{% endblock %}



myblog3/music/templates/music/form-template.html
{%for field in form %}
    <div class="form-group">
        <div class=" col sm-offset-2 col-sm-10">
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small">{{ field.errors }}</span>
            </div>
            <label class="control-label col-sm-2">{{field.label_tag}}</label>
            <div class="col-sm-10">{{field}}</div>

        </div>
    </div>
{%endfor%}

myblog3/music/templates/music/index.html
{%extends 'music/base.html'%}
{%block title%}Viberr{%endblock%}


{% block body %}
<h3 class="bg-primary">Albums.</h3>

<div class ="container-fluid">
  <div class="row">
	  {%for album in all_album%}
    	<div class="thumbnail album-cover col-ls-3 col-md-4 col-sm-6 col-xs-12">
    	  <div class="well">
	        <img class="img-thumbnail center" src="{{album.album_logo}}">

	      </div>
	      <div class="">
	        <div class="well">
				<a href="{%url 'music:detail' album.id %}"><b>{{album.album_title}}</b></a>
	        </div>
	        <div class="well">
    	      {{album.artist }}
    	    </div>
    	    <div class="Albumtools">
    	      <div class="thumbnail">dad da da</div>
    	      <div class="thumbnail favouriteAlbum"><span class="glyphicon glyphicon-star" ></span></div>
    	      <div class="thumbnail deleteAlbum"><span class="glyphicon glyphicon-trash" ></span></div>
    	    </div>
    	  </div>
    	</div>
	  {%endfor%}


  </div>


</div>














{% endblock %}